Repository 100-hours-a-week/20-real-be, pull requests merged in 2025-05, with the labels that each got.

#23 :sparkles: feat: HealthCheck API 개발
  src/main/java/com/real/backend/config/SecurityConfig.java
  src/main/java/com/real/backend/security/filter/JwtFilter.java
  src/main/java/com/real/backend/test/HealthCheckController.java
Labels: ✨ Feature

#40 Feat/user/#11
  src/main/java/com/real/backend/config/SecurityConfig.java
  src/main/java/com/real/backend/domain/chatbot/ChatbotController.java
  src/main/java/com/real/backend/domain/news/component/NewsFinder.java
  src/main/java/com/real/backend/domain/news/controller/NewsCommentController.java
  src/main/java/com/real/backend/domain/news/controller/NewsController.java
  src/main/java/com/real/backend/domain/news/controller/NewsLikeController.java
  src/main/java/com/real/backend/domain/news/service/NewsService.java
  src/main/java/com/real/backend/domain/notice/controller/NoticeCommentController.java
  src/main/java/com/real/backend/domain/notice/controller/NoticeController.java
  src/main/java/com/real/backend/domain/notice/controller/NoticeLikeController.java
  src/main/java/com/real/backend/domain/notice/repository/NoticeRepository.java
  src/main/java/com/real/backend/domain/notice/service/NoticeService.java
  src/main/java/com/real/backend/domain/oauth/controller/KakaoController.java
  src/main/java/com/real/backend/domain/user/UserController.java
  src/main/java/com/real/backend/domain/user/domain/User.java
  src/main/java/com/real/backend/domain/user/domain/UserNoticeRead.java
  src/main/java/com/real/backend/domain/user/dto/UserUnreadNoticeResponseDTO.java
  src/main/java/com/real/backend/domain/user/repository/UserNoticeReadRepository.java
  src/main/java/com/real/backend/domain/user/service/UserService.java
  src/main/java/com/real/backend/domain/user/service/UserSignupService.java
Labels: ✨ Feature

#46 refactor: 쿠키 secure 옵션 설정 변경
  src/main/java/com/real/backend/domain/oauth/service/AuthService.java
Labels: ⚙ Setting

#63 fix: 댓글 작성시 createdAt이 Null인 버그 수정
  src/main/java/com/real/backend/domain/notice/domain/Notice.java
  src/main/java/com/real/backend/global/BaseEntity.java
Labels: 🐞 BugFix

#64 ♻️ refactor: Notice 생성하는 파일들 이름 변경
  build.gradle
  src/main/java/com/real/backend/domain/notice/controller/NoticeController.java
  src/main/java/com/real/backend/domain/notice/domain/Notice.java
  src/main/java/com/real/backend/domain/notice/dto/NoticePasteRequestTmpDTO.java
  src/main/java/com/real/backend/domain/notice/service/NoticeService.java
  src/main/java/com/real/backend/domain/notice/tmp/NoticeTmpController.java
  src/main/java/com/real/backend/domain/notice/tmp/NoticeTmpService.java
Labels: 🔨 Refactor

#67 ♻️ refactor: 검증 관련 로직 추가 및 수정
  build.gradle
  src/main/java/com/real/backend/domain/chatbot/ChatbotController.java
  src/main/java/com/real/backend/domain/news/controller/NewsCommentController.java
  src/main/java/com/real/backend/domain/news/controller/NewsController.java
  src/main/java/com/real/backend/domain/news/dto/NewsCommentRequestDTO.java
  src/main/java/com/real/backend/domain/news/dto/NewsCreateRequestDTO.java
  src/main/java/com/real/backend/domain/notice/controller/NoticeCommentController.java
  src/main/java/com/real/backend/domain/notice/controller/NoticeController.java
  src/main/java/com/real/backend/domain/notice/dto/NoticeCommentRequestDTO.java
  src/main/java/com/real/backend/domain/notice/dto/NoticeCreateRequestDTO.java
  src/main/java/com/real/backend/domain/notice/dto/NoticePasteRequestDTO.java
  src/main/java/com/real/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/real/backend/infra/ai/dto/ChatbotRequestDTO.java
  src/main/java/com/real/backend/infra/ai/dto/NewsAiRequestDTO.java
  src/main/java/com/real/backend/infra/ai/dto/NoticeSummaryRequestDTO.java
Labels: 🔨 Refactor

#68 ♻️ fix: 파일 이름이 저장되지 않던 버그 수정
  src/main/java/com/real/backend/domain/notice/service/NoticeFileService.java
Labels: 🐞 BugFix

#70 ✨ feat: xss 필터링 기능 추가
  build.gradle
  src/main/java/com/real/backend/domain/news/dto/NewsCommentRequestDTO.java
  src/main/java/com/real/backend/domain/news/dto/NewsCreateRequestDTO.java
  src/main/java/com/real/backend/domain/news/service/NewsCommentService.java
  src/main/java/com/real/backend/domain/news/service/NewsService.java
  src/main/java/com/real/backend/domain/notice/controller/NoticeCommentController.java
  src/main/java/com/real/backend/domain/notice/domain/Notice.java
  src/main/java/com/real/backend/domain/notice/dto/NoticeCommentRequestDTO.java
  src/main/java/com/real/backend/domain/notice/dto/NoticeCreateRequestDTO.java
  src/main/java/com/real/backend/domain/notice/dto/NoticePasteRequestDTO.java
  src/main/java/com/real/backend/domain/notice/service/NoticeCommentService.java
  src/main/java/com/real/backend/domain/notice/service/NoticeService.java
  src/main/java/com/real/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/real/backend/global/aop/Sanitizer.java
  src/main/java/com/real/backend/global/aop/XssSanitizer.java
  src/main/java/com/real/backend/global/aop/XssSanitizerAspect.java
  src/main/java/com/real/backend/infra/ai/dto/ChatbotRequestDTO.java
  src/main/java/com/real/backend/infra/ai/dto/NewsAiRequestDTO.java
Labels: ✨ Feature

#71 🐛fix: 챗봇에 값이 안들어가던 버그 수정
  src/main/java/com/real/backend/domain/oauth/domain/RefreshToken.java
  src/main/java/com/real/backend/domain/oauth/repository/RefreshTokenRepository.java
  src/main/java/com/real/backend/domain/oauth/service/AuthService.java
  src/main/java/com/real/backend/domain/user/domain/User.java
  src/main/java/com/real/backend/infra/ai/dto/ChatbotRequestDTO.java
Labels: 🐞 BugFix

#77 setting: merge branch 생성 후 main branch로 merge
  .editorconfig
  .env
  .gitattributes
  .gitmodules
  appspec.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  scripts/start.sh
  scripts/stop.sh
  settings.gradle
  src/main/java/com/real/backend/config/QueryDslConfig.java
  src/main/java/com/real/backend/domain/news/dto/NewsLikeResponseDTO.java
  src/main/java/com/real/backend/domain/news/dto/NewsResponseDTO.java
  src/main/java/com/real/backend/domain/news/repository/NewsCommentRepository.java
  src/main/java/com/real/backend/domain/news/repository/NewsLikeRepository.java
  src/main/java/com/real/backend/domain/notice/domain/Notice.java
  src/main/java/com/real/backend/domain/notice/service/NoticeService.java
  src/main/java/com/real/backend/domain/oauth/controller/AuthController.java
  src/main/java/com/real/backend/domain/oauth/dto/KakaoProfileDTO.java
  src/main/java/com/real/backend/domain/oauth/dto/KakaoTokenDTO.java
  src/main/java/com/real/backend/domain/oauth/kakao/KakaoUtil.java
  src/main/java/com/real/backend/domain/oauth/repository/RefreshTokenRepository.java
  src/main/java/com/real/backend/domain/oauth/service/AuthService.java
  src/main/java/com/real/backend/domain/user/domain/LoginType.java
  src/main/java/com/real/backend/domain/user/domain/Role.java
  src/main/java/com/real/backend/domain/user/domain/Status.java
  src/main/java/com/real/backend/domain/user/repository/InvitedUserRepository.java
  src/main/java/com/real/backend/exception/BadRequestException.java
  src/main/java/com/real/backend/exception/ConfilctException.java
  src/main/java/com/real/backend/exception/ForbiddenException.java
  src/main/java/com/real/backend/exception/IOException.java
  src/main/java/com/real/backend/exception/NotFoundException.java
  src/main/java/com/real/backend/exception/ServerException.java
  src/main/java/com/real/backend/global/BaseEntity.java
  src/main/java/com/real/backend/response/DataResponse.java
  src/main/java/com/real/backend/response/ResponseDTO.java
  src/main/java/com/real/backend/response/StatusCode.java
  src/main/java/com/real/backend/response/StatusResponse.java
  src/main/java/com/real/backend/security/CurrentSession.java
  src/main/java/com/real/backend/security/CustomUserDetailsService.java
  src/main/java/com/real/backend/security/JwtUtil.java
  src/main/java/com/real/backend/security/Session.java
  src/main/java/com/real/backend/security/dto/CustomUserDetails.java
  src/main/java/com/real/backend/security/dto/TokenResponse.java
  src/main/java/com/real/backend/security/filter/CustomLoginFilter.java
  src/main/java/com/real/backend/security/filter/JwtFilter.java
  src/main/java/com/real/backend/test/HealthCheckController.java
  src/main/java/com/real/backend/util/CONSTANT.java
  src/main/java/com/real/backend/util/CookieUtils.java
  src/main/java/com/real/backend/util/CursorUtils.java
  src/main/java/com/real/backend/util/dto/SliceDTO.java
  src/test/java/com/real/backend/BackendApplicationTests.java
Labels: ⚙ Setting

#81 ♻️ refactor: 뉴스의 응답 생성 날짜 포맷 변경
  src/main/java/com/real/backend/domain/news/dto/NewsResponseDTO.java
Labels: 🔨 Refactor

#82 🐛️ fix: transactional 어노테이션 추가
  src/main/java/com/real/backend/domain/auth/service/AuthService.java
Labels: 🐞 BugFix

#83 ♻️️ refactor: access token이 담긴 쿠키의 유효 기간 수정
  src/main/java/com/real/backend/util/CookieUtils.java
Labels: 🔨 Refactor

#95 ✨ feat: 토큰 재발급 기능 구현
  src/main/java/com/real/backend/config/SecurityConfig.java
  src/main/java/com/real/backend/domain/auth/service/AuthService.java
  src/main/java/com/real/backend/security/filter/JwtFilter.java
Labels: ✨ Feature

#108 🐛 fix: 공지 생성시 날짜 반영 안되는 버그 수정
  build.gradle
  src/main/java/com/real/backend/batch/PostCountScheduler.java
  src/main/java/com/real/backend/config/RedisConfig.java
  src/main/java/com/real/backend/domain/news/controller/NewsController.java
  src/main/java/com/real/backend/domain/news/domain/News.java
  src/main/java/com/real/backend/domain/news/dto/NewsResponseDTO.java
  src/main/java/com/real/backend/domain/news/repository/NewsRepository.java
  src/main/java/com/real/backend/domain/news/service/NewsCommentService.java
  src/main/java/com/real/backend/domain/news/service/NewsService.java
  src/main/java/com/real/backend/domain/notice/controller/NoticeController.java
  src/main/java/com/real/backend/domain/notice/dto/NoticeInfoResponseDTO.java
  src/main/java/com/real/backend/domain/notice/repository/NoticeRepository.java
  src/main/java/com/real/backend/domain/notice/service/NoticeCommentService.java
  src/main/java/com/real/backend/domain/notice/service/NoticeService.java
  src/main/java/com/real/backend/infra/redis/PostRedisService.java
  src/main/java/com/real/backend/post/Post.java
Labels: 🐞 BugFix

#121 🐛fix: 데이터베이스 동시성 문제 해결
  src/main/java/com/real/backend/domain/news/controller/NewsCommentController.java
  src/main/java/com/real/backend/domain/news/controller/NewsLikeController.java
  src/main/java/com/real/backend/domain/news/domain/NewsLike.java
  src/main/java/com/real/backend/domain/news/repository/NewsLikeRepository.java
  src/main/java/com/real/backend/domain/news/repository/NewsRepository.java
  src/main/java/com/real/backend/domain/news/service/NewsCommentService.java
  src/main/java/com/real/backend/domain/news/service/NewsLikeService.java
  src/main/java/com/real/backend/domain/news/service/NewsService.java
  src/main/java/com/real/backend/domain/notice/controller/NoticeCommentController.java
  src/main/java/com/real/backend/domain/notice/controller/NoticeLikeController.java
  src/main/java/com/real/backend/domain/notice/domain/NoticeLike.java
  src/main/java/com/real/backend/domain/notice/repository/NoticeLikeRepository.java
  src/main/java/com/real/backend/domain/notice/repository/NoticeRepository.java
  src/main/java/com/real/backend/domain/notice/service/NoticeCommentService.java
  src/main/java/com/real/backend/domain/notice/service/NoticeLikeService.java
  src/main/java/com/real/backend/domain/notice/service/NoticeService.java
  src/main/java/com/real/backend/domain/user/component/UserFinder.java
  src/main/java/com/real/backend/domain/user/domain/UserNoticeRead.java
  src/main/java/com/real/backend/domain/user/repository/UserNoticeReadRepository.java
  src/main/java/com/real/backend/post/Post.java
Labels: 🐞 BugFix

#128 🐛 fix: 댓글 삭제 동시성 문제 해결
  src/main/java/com/real/backend/domain/news/controller/NewsCommentController.java
  src/main/java/com/real/backend/domain/news/dto/NewsStressResponseDTO.java
  src/main/java/com/real/backend/domain/news/repository/NewsCommentRepository.java
  src/main/java/com/real/backend/domain/news/repository/NewsRepository.java
  src/main/java/com/real/backend/domain/news/service/NewsCommentService.java
  src/main/java/com/real/backend/domain/news/service/NewsService.java
  src/main/java/com/real/backend/domain/notice/controller/NoticeCommentController.java
  src/main/java/com/real/backend/domain/notice/dto/NoticeStressResponseDTO.java
  src/main/java/com/real/backend/domain/notice/repository/NoticeCommentRepository.java
  src/main/java/com/real/backend/domain/notice/repository/NoticeRepository.java
  src/main/java/com/real/backend/domain/notice/service/NoticeCommentService.java
  src/main/java/com/real/backend/domain/notice/service/NoticeService.java
Labels: 🐞 BugFix

#139 ✨ feat: 테스트를 위한 회원가입 기능 추가
  src/main/java/com/real/backend/batch/NewsSyncScheduler.java
  src/main/java/com/real/backend/batch/NoticeSyncScheduler.java
  src/main/java/com/real/backend/config/RedisConfig.java
  src/main/java/com/real/backend/config/SecurityConfig.java
  src/main/java/com/real/backend/domain/news/dto/NewsCreateRequestDTO.java
  src/main/java/com/real/backend/domain/notice/service/NoticeService.java
  src/main/java/com/real/backend/security/Session.java
  src/main/java/com/real/backend/security/filter/JwtFilter.java
  src/main/java/com/real/backend/test/TokenGenController.java
  src/main/java/com/real/backend/test/UserRequestDTO.java
Labels: ✨ Feature

#142 ✨ feat: 성능 테스트를 위해 자체 회원가입, 로그인 api 추가
  src/main/java/com/real/backend/config/SecurityConfig.java
  src/main/java/com/real/backend/domain/chatbot/ChatbotController.java
  src/main/java/com/real/backend/infra/ai/dto/ChatbotRequestDTO.java
  src/main/java/com/real/backend/infra/ai/service/ChatbotService.java
Labels: ✨ Feature
